In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
gdf = gpd.read_file("./data/tracts2019/PA/tl_2019_42_tract.shp")
gdf["GEOID"] = gdf["GEOID"].astype(int)
gdf.head()

ERROR 1: PROJ: proj_create_from_database: Open of /home/hbaier/.conda/envs/lmtest/share/proj failed

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,42,125,775200,42125775200,7752,Census Tract 7752,G5020,S,2917348,177674,+40.1838983,-079.8643068,"POLYGON ((-79.87659 40.17755, -79.87623 40.178..."
1,42,125,775300,42125775300,7753,Census Tract 7753,G5020,S,2002316,206996,+40.1719715,-079.8615530,"POLYGON ((-79.87929 40.17486, -79.87845 40.175..."
2,42,125,782700,42125782700,7827,Census Tract 7827,G5020,S,665661,97121,+40.1503939,-079.9081484,"POLYGON ((-79.91356 40.15326, -79.91333 40.153..."
3,42,125,783200,42125783200,7832,Census Tract 7832,G5020,S,921763,73590,+40.1424281,-079.9041835,"POLYGON ((-79.91142 40.14456, -79.90932 40.145..."
4,42,125,783300,42125783300,7833,Census Tract 7833,G5020,S,1052144,185589,+40.1348221,-079.8972986,"POLYGON ((-79.90631 40.13747, -79.90622 40.137..."

In [3]:
df = pd.read_csv("./final_wealth_indices_2019.csv")
df.head()

,NAME,median_home_value,median_year_built,median_gross_rent,median_rooms,total_housing_units,owner_occupied_units,total_units_in_structure,units_1_detached,units_1_attached,...,wealth_index_property,wealth_quintile_property,wealth_index_transport,wealth_quintile_transport,wealth_index_financial,wealth_quintile_financial,wealth_index_utilities,wealth_quintile_utilities,wealth_index_satellite_visible,wealth_quintile_satellite_visible
0,"Census Tract 11, Jefferson County, Alabama",85500.0,1978.0,621.0,5.9,1851,1047,2103,1550,13,...,-0.713404,Poor,-0.006717,Middle,0.395494,Middle,-0.565841,Poor,-0.902011,Poorest
1,"Census Tract 14, Jefferson County, Alabama",67800.0,1953.0,738.0,5.4,816,506,1148,933,24,...,-0.774170,Poor,0.228657,Middle,-1.100118,Poorest,-0.639027,Poor,-0.943808,Poorest
2,"Census Tract 20, Jefferson County, Alabama",68400.0,1957.0,692.0,5.2,1419,534,1836,1129,44,...,-1.271153,Poorest,-0.723010,Poorest,-2.980733,Poorest,-2.302698,Poorest,-1.223734,Poorest
3,"Census Tract 38.02, Jefferson County, Alabama",64100.0,1955.0,876.0,5.5,1894,1024,2477,2286,0,...,-0.653287,Poor,0.212850,Middle,-0.928226,Poorest,-1.744399,Poorest,-0.691056,Poor
4,"Census Tract 40, Jefferson County, Alabama",67300.0,1965.0,594.0,4.4,1429,374,1962,830,10,...,-1.788903,Poorest,-2.002893,Poorest,-2.947440,Poorest,-2.904242,Poorest,-1.816713,Poorest

In [4]:
ca = df[df["geoid"].isin(gdf["GEOID"])][["geoid", "wealth_index_overall_core"]]
ca.head()

             geoid  wealth_index_overall_core
55345  42125744200                  -0.575887
55346  42125754500                  -0.354516
55347  42125755100                  -0.196749
55348  42125771200                   0.048051
55349  42049010304                   1.023612

In [5]:
ca.to_csv("./pa_wi2019.csv", index = False)

In [6]:
ca = ca.rename(columns = {"geoid": "GEOID"})

In [7]:
df['geoid']

0         1073001100
1         1073001400
2         1073002000
3         1073003802
4         1073004000
            ...
73051    56021001902
73052    56021980801
73053    56025001602
73054    56025001603
73055    56029965100
Name: geoid, Length: 73056, dtype: int64

In [8]:
gdf["GEOID"].astype(int)

0       42125775200
1       42125775300
2       42125782700
3       42125783200
4       42125783300
           ...
3213    42017100103
3214    42091201411
3215    42017100104
3216    42017100105
3217    42017100206
Name: GEOID, Length: 3218, dtype: int64

In [9]:
ca.shape

(3218, 2)

In [10]:
pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/PA/tl_2019_42_tract.shp")

/tmp/ipykernel_1075192/2327660158.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/PA/tl_2019_42_tract.shp")
/home/hbaier/.conda/envs/lmtest/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'wealth_index_overall_core' to 'wealth_ind'
  ogr_write(