In [11]:
import geopandas as gpd
import pandas as pd

In [12]:
gdf = gpd.read_file("./data/tracts2019/AZ/tl_2019_04_tract.shp")
gdf["GEOID"] = gdf["GEOID"].astype(int)
gdf.head()

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,04,013,618300,4013618300,6183,Census Tract 6183,G5020,S,1413808,0,+33.6433998,-112.1431656,"POLYGON ((-112.15187 33.64732, -112.1512 33.64..."
1,04,013,116605,4013116605,1166.05,Census Tract 1166.05,G5020,S,2581154,0,+33.3848158,-112.1596188,"POLYGON ((-112.16832 33.38711, -112.16826 33.3..."
2,04,013,116606,4013116606,1166.06,Census Tract 1166.06,G5020,S,2577692,0,+33.3848675,-112.1423292,"POLYGON ((-112.15102 33.38, -112.15101 33.3812..."
3,04,013,811200,4013811200,8112,Census Tract 8112,G5020,S,2703576,0,+33.2986821,-111.8852410,"POLYGON ((-111.89451 33.29548, -111.89442 33.2..."
4,04,013,216848,4013216848,2168.48,Census Tract 2168.48,G5020,S,13398918,0,+33.5928636,-111.7877587,"POLYGON ((-111.83131 33.5897, -111.82871 33.58..."

In [13]:
df = pd.read_csv("./final_wealth_indices_2019.csv")
df.head()

,NAME,median_home_value,median_year_built,median_gross_rent,median_rooms,total_housing_units,owner_occupied_units,total_units_in_structure,units_1_detached,units_1_attached,...,wealth_index_property,wealth_quintile_property,wealth_index_transport,wealth_quintile_transport,wealth_index_financial,wealth_quintile_financial,wealth_index_utilities,wealth_quintile_utilities,wealth_index_satellite_visible,wealth_quintile_satellite_visible
0,"Census Tract 11, Jefferson County, Alabama",85500.0,1978.0,621.0,5.9,1851,1047,2103,1550,13,...,-0.713404,Poor,-0.006717,Middle,0.395494,Middle,-0.565841,Poor,-0.902011,Poorest
1,"Census Tract 14, Jefferson County, Alabama",67800.0,1953.0,738.0,5.4,816,506,1148,933,24,...,-0.774170,Poor,0.228657,Middle,-1.100118,Poorest,-0.639027,Poor,-0.943808,Poorest
2,"Census Tract 20, Jefferson County, Alabama",68400.0,1957.0,692.0,5.2,1419,534,1836,1129,44,...,-1.271153,Poorest,-0.723010,Poorest,-2.980733,Poorest,-2.302698,Poorest,-1.223734,Poorest
3,"Census Tract 38.02, Jefferson County, Alabama",64100.0,1955.0,876.0,5.5,1894,1024,2477,2286,0,...,-0.653287,Poor,0.212850,Middle,-0.928226,Poorest,-1.744399,Poorest,-0.691056,Poor
4,"Census Tract 40, Jefferson County, Alabama",67300.0,1965.0,594.0,4.4,1429,374,1962,830,10,...,-1.788903,Poorest,-2.002893,Poorest,-2.947440,Poorest,-2.904242,Poorest,-1.816713,Poorest

In [22]:
df.columns

Index(['NAME', 'median_home_value', 'median_year_built', 'median_gross_rent',
       'median_rooms', 'total_housing_units', 'owner_occupied_units',
       'total_units_in_structure', 'units_1_detached', 'units_1_attached',
       'total_bedrooms', 'crowding_total_households',
       'owner_crowded_1_01_to_1_50_occupants',
       'owner_severely_crowded_1_51_plus_occupants',
       'renter_crowded_1_01_to_1_50_occupants',
       'renter_severely_crowded_1_51_plus_occupants',
       'vehicles_total_households', 'owner_1_vehicle', 'owner_2_vehicles',
       'owner_3_plus_vehicles', 'renter_1_vehicle', 'renter_2_vehicles',
       'renter_3_plus_vehicles', 'internet_total_households',
       'broadband_internet', 'heating_total_households', 'utility_gas_heat',
       'electricity_heat', 'fuel_oil_kerosene_heat', 'wood_heat',
       'median_household_income', 'per_capita_income',
       'poverty_total_population', 'population_below_poverty_line',
       'labor_force_total', 'unemployed', 'rent_burden_universe',
       'rent_burdened_30_34', 'rent_burdened_35_39', 'rent_burdened_40_49',
       'rent_burdened_50_plus', 'owner_mortgage_universe',
       'owner_mortgaged_units', 'owner_mortgaged_30_34',
       'owner_mortgaged_35_39', 'owner_mortgaged_40_49',
       'owner_mortgaged_50_plus', 'state', 'county', 'tract', 'geoid',
       'log_home_value', 'owner_pct', 'crowded_pct', 'severely_crowded_pct',
       'pct_no_vehicle', 'pct_2plus_vehicles', 'modern_heat_pct',
       'poor_heat_pct', 'gas_heat_pct', 'poverty_rate', 'log_gross_rent',
       'single_family_pct', 'unemployment_rate', 'rent_burdened_30plus_pct',
       'owner_burdened_30plus_pct', 'broadband_pct',
       'wealth_index_overall_core', 'wealth_quintile_overall_core',
       'wealth_index_overall_extended', 'wealth_quintile_overall_extended',
       'wealth_index_property', 'wealth_quintile_property',
       'wealth_index_transport', 'wealth_quintile_transport',
       'wealth_index_financial', 'wealth_quintile_financial',
       'wealth_index_utilities', 'wealth_quintile_utilities',
       'wealth_index_satellite_visible', 'wealth_quintile_satellite_visible'],
      dtype='str')

In [14]:
ca = df[df["geoid"].isin(gdf["GEOID"])][["geoid", "wealth_index_overall_core"]]
ca.head()

           geoid  wealth_index_overall_core
1348  4005002200                   1.079235
1349  4005002300                  -0.281248
1350  4005942201                  -1.827890
1351  4005942202                  -2.785213
1352  4005944900                  -1.872198

In [15]:
ca.to_csv("./az_wi2019.csv", index = False)

In [16]:
ca = ca.rename(columns = {"geoid": "GEOID"})

In [17]:
df['geoid']

0         1073001100
1         1073001400
2         1073002000
3         1073003802
4         1073004000
            ...
73051    56021001902
73052    56021980801
73053    56025001602
73054    56025001603
73055    56029965100
Name: geoid, Length: 73056, dtype: int64

In [18]:
gdf["GEOID"].astype(int)

0       4013618300
1       4013116605
2       4013116606
3       4013811200
4       4013216848
           ...
1521    4019003003
1522    4019003707
1523    4019004067
1524    4019003303
1525    4019003706
Name: GEOID, Length: 1526, dtype: int64

In [19]:
ca.shape

(1526, 2)

In [20]:
pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/AZ/tl_2019_04_tract_wi.shp")

/tmp/ipykernel_574367/549538126.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/AZ/tl_2019_04_tract_wi.shp")
/home/hbaier/.conda/envs/lmtest/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'wealth_index_overall_core' to 'wealth_ind'
  ogr_write(