In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
gdf = gpd.read_file("./data/tracts2019/CA/tl_2019_06_tract.shp")
gdf["GEOID"] = gdf["GEOID"].astype(int)
gdf.head()

ERROR 1: PROJ: proj_create_from_database: Open of /home/hbaier/.conda/envs/lmtest/share/proj failed

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,06,037,139301,6037139301,1393.01,Census Tract 1393.01,G5020,S,2865657,0,+34.1781538,-118.5581265,"POLYGON ((-118.5715 34.17758, -118.57148 34.17..."
1,06,037,139302,6037139302,1393.02,Census Tract 1393.02,G5020,S,338289,0,+34.1767230,-118.5383655,"POLYGON ((-118.54073 34.1802, -118.5407 34.180..."
2,06,037,139502,6037139502,1395.02,Census Tract 1395.02,G5020,S,1047548,0,+34.1628402,-118.5263110,"POLYGON ((-118.53224 34.16201, -118.53177 34.1..."
3,06,037,139600,6037139600,1396,Census Tract 1396,G5020,S,2477482,0,+34.1640599,-118.5101001,"POLYGON ((-118.51858 34.15858, -118.51858 34.1..."
4,06,037,139701,6037139701,1397.01,Census Tract 1397.01,G5020,S,3396396,2411,+34.1574290,-118.4954117,"POLYGON ((-118.5098 34.15691, -118.50848 34.15..."

In [3]:
df = pd.read_csv("./final_wealth_indices_2019.csv")
df.head()

,NAME,median_home_value,median_year_built,median_gross_rent,median_rooms,total_housing_units,owner_occupied_units,total_units_in_structure,units_1_detached,units_1_attached,...,wealth_index_property,wealth_quintile_property,wealth_index_transport,wealth_quintile_transport,wealth_index_financial,wealth_quintile_financial,wealth_index_utilities,wealth_quintile_utilities,wealth_index_satellite_visible,wealth_quintile_satellite_visible
0,"Census Tract 11, Jefferson County, Alabama",85500.0,1978.0,621.0,5.9,1851,1047,2103,1550,13,...,-0.713404,Poor,-0.006717,Middle,0.395494,Middle,-0.565841,Poor,-0.902011,Poorest
1,"Census Tract 14, Jefferson County, Alabama",67800.0,1953.0,738.0,5.4,816,506,1148,933,24,...,-0.774170,Poor,0.228657,Middle,-1.100118,Poorest,-0.639027,Poor,-0.943808,Poorest
2,"Census Tract 20, Jefferson County, Alabama",68400.0,1957.0,692.0,5.2,1419,534,1836,1129,44,...,-1.271153,Poorest,-0.723010,Poorest,-2.980733,Poorest,-2.302698,Poorest,-1.223734,Poorest
3,"Census Tract 38.02, Jefferson County, Alabama",64100.0,1955.0,876.0,5.5,1894,1024,2477,2286,0,...,-0.653287,Poor,0.212850,Middle,-0.928226,Poorest,-1.744399,Poorest,-0.691056,Poor
4,"Census Tract 40, Jefferson County, Alabama",67300.0,1965.0,594.0,4.4,1429,374,1962,830,10,...,-1.788903,Poorest,-2.002893,Poorest,-2.947440,Poorest,-2.904242,Poorest,-1.816713,Poorest

In [4]:
ca = df[df["geoid"].isin(gdf["GEOID"])][["geoid", "wealth_index_overall_core"]]
ca.head()

           geoid  wealth_index_overall_core
3560  6085507904                   2.817919
3561  6085508504                   0.155499
3562  6085508505                   1.412460
3563  6085508704                   0.697139
3564  6085509403                  -0.523760

In [5]:
ca.to_csv("./ca_wi2019.csv", index = False)

In [9]:
ca = ca.rename(columns = {"geoid": "GEOID"})

In [10]:
df['geoid']

0         1073001100
1         1073001400
2         1073002000
3         1073003802
4         1073004000
            ...
73051    56021001902
73052    56021980801
73053    56025001602
73054    56025001603
73055    56029965100
Name: geoid, Length: 73056, dtype: int64

In [11]:
gdf["GEOID"].astype(int)

0       6037139301
1       6037139302
2       6037139502
3       6037139600
4       6037139701
           ...
8052    6001443001
8053    6001443002
8054    6001443102
8055    6001443301
8056    6037137501
Name: GEOID, Length: 8057, dtype: int64

In [12]:
ca.shape

(8057, 2)

In [15]:
pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/CA/tl_2019_06_tract_wi.shp")

/tmp/ipykernel_2855980/3825557211.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/CA/tl_2019_06_tract_wi.shp")
/home/hbaier/.conda/envs/lmtest/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'wealth_index_overall_core' to 'wealth_ind'
  ogr_write(