In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
gdf = gpd.read_file("./data/tracts2019/GA/tl_2019_13_tract.shp")
gdf["GEOID"] = gdf["GEOID"].astype(int)
gdf.head()

ERROR 1: PROJ: proj_create_from_database: Open of /home/hbaier/.conda/envs/lmtest/share/proj failed

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,13,127,990000,13127990000,9900,Census Tract 9900,G5020,S,0,255438863,+31.1427304,-081.3044534,"POLYGON ((-81.41082 31.02597, -81.40981 31.028..."
1,13,135,050311,13135050311,503.11,Census Tract 503.11,G5020,S,4923609,6728,+33.9485370,-084.2126207,"POLYGON ((-84.23193 33.9491, -84.23162 33.9492..."
2,13,051,010501,13051010501,105.01,Census Tract 105.01,G5020,S,33598831,687051,+32.0535751,-081.1761253,"POLYGON ((-81.21466 32.04782, -81.21459 32.048..."
3,13,051,011104,13051011104,111.04,Census Tract 111.04,G5020,S,6362337,518621,+32.0196721,-080.9708372,"POLYGON ((-80.99249 32.01881, -80.99223 32.019..."
4,13,051,011004,13051011004,110.04,Census Tract 110.04,G5020,S,19631793,4163375,+31.9734729,-081.0604216,"POLYGON ((-81.09843 31.94203, -81.0982 31.9432..."

In [3]:
df = pd.read_csv("./final_wealth_indices_2019.csv")
df.head()

,NAME,median_home_value,median_year_built,median_gross_rent,median_rooms,total_housing_units,owner_occupied_units,total_units_in_structure,units_1_detached,units_1_attached,...,wealth_index_property,wealth_quintile_property,wealth_index_transport,wealth_quintile_transport,wealth_index_financial,wealth_quintile_financial,wealth_index_utilities,wealth_quintile_utilities,wealth_index_satellite_visible,wealth_quintile_satellite_visible
0,"Census Tract 11, Jefferson County, Alabama",85500.0,1978.0,621.0,5.9,1851,1047,2103,1550,13,...,-0.713404,Poor,-0.006717,Middle,0.395494,Middle,-0.565841,Poor,-0.902011,Poorest
1,"Census Tract 14, Jefferson County, Alabama",67800.0,1953.0,738.0,5.4,816,506,1148,933,24,...,-0.774170,Poor,0.228657,Middle,-1.100118,Poorest,-0.639027,Poor,-0.943808,Poorest
2,"Census Tract 20, Jefferson County, Alabama",68400.0,1957.0,692.0,5.2,1419,534,1836,1129,44,...,-1.271153,Poorest,-0.723010,Poorest,-2.980733,Poorest,-2.302698,Poorest,-1.223734,Poorest
3,"Census Tract 38.02, Jefferson County, Alabama",64100.0,1955.0,876.0,5.5,1894,1024,2477,2286,0,...,-0.653287,Poor,0.212850,Middle,-0.928226,Poorest,-1.744399,Poorest,-0.691056,Poor
4,"Census Tract 40, Jefferson County, Alabama",67300.0,1965.0,594.0,4.4,1429,374,1962,830,10,...,-1.788903,Poorest,-2.002893,Poorest,-2.947440,Poorest,-2.904242,Poorest,-1.816713,Poorest

In [4]:
ca = df[df["geoid"].isin(gdf["GEOID"])][["geoid", "wealth_index_overall_core"]]
ca.head()

             geoid  wealth_index_overall_core
18341  13135050709                   0.281886
18342  13135050314                  -0.790414
18343  13135050315                  -0.680747
18344  13135050415                   0.740436
18345  13135050425                   1.028141

In [6]:
ca.to_csv("./ga_wi2019.csv", index = False)

In [7]:
ca = ca.rename(columns = {"geoid": "GEOID"})

In [8]:
df['geoid']

0         1073001100
1         1073001400
2         1073002000
3         1073003802
4         1073004000
            ...
73051    56021001902
73052    56021980801
73053    56025001602
73054    56025001603
73055    56029965100
Name: geoid, Length: 73056, dtype: int64

In [9]:
gdf["GEOID"].astype(int)

0       13127990000
1       13135050311
2       13051010501
3       13051011104
4       13051011004
           ...
1964    13089023315
1965    13089023421
1966    13089021411
1967    13089021416
1968    13089021504
Name: GEOID, Length: 1969, dtype: int64

In [10]:
ca.shape

(1969, 2)

In [11]:
pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/GA/tl_2019_13_tract_wi.shp")

/tmp/ipykernel_825812/1161065366.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  pd.merge(gdf, ca, on = "GEOID").to_file("./data/tracts2019/GA/tl_2019_13_tract_wi.shp")
/home/hbaier/.conda/envs/lmtest/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'wealth_index_overall_core' to 'wealth_ind'
  ogr_write(